export const EDUCATION_LEVELS = [
  "Primary Level Education",
  "Trade Certificate",
  "High School Diploma",
  "O'levels/CXC/CSEC",
  "A'levels/CAPE",
  "Associate's Degree",
  "Bachelor's Degree",
  "Post Graduate Degree",
  "Master's Degree",
  "PhD",
];

export const COUNTRIES = [
  "Jamaica",
  "Trinidad and Tobago",
  "Barbados",
  "Bahamas",
  "Guyana",
  "Belize",
  "Antigua and Barbuda",
  "Dominica",
  "Grenada",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Suriname",
  "Haiti",
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Nigeria",
  "Ghana",
  "India",
];

export const PARISHES_BY_COUNTRY: Record<string, string[]> = {
  Jamaica: [
    "Kingston",
    "St. Andrew",
    "St. Thomas",
    "Portland",
    "St. Mary",
    "St. Ann",
    "Trelawny",
    "St. James",
    "Hanover",
    "Westmoreland",
    "St. Elizabeth",
    "Manchester",
    "Clarendon",
    "St. Catherine",
  ],
  "Trinidad and Tobago": [
    "Port of Spain",
    "San Fernando",
    "Chaguanas",
    "Arima",
    "Point Fortin",
    "Diego Martin",
    "Tunapuna/Piarco",
    "San Juan/Laventille",
    "Couva-Tabaquite-Talparo",
    "Sangre Grande",
    "Siparia",
    "Penal-Debe",
    "Princes Town",
    "Mayaro/Rio Claro",
    "Tobago",
  ],
  Barbados: [
    "Christ Church",
    "St. Andrew",
    "St. George",
    "St. James",
    "St. John",
    "St. Joseph",
    "St. Lucy",
    "St. Michael",
    "St. Peter",
    "St. Philip",
    "St. Thomas",
  ],
  Bahamas: ["New Providence", "Grand Bahama", "Abaco", "Andros", "Eleuthera", "Exuma", "Long Island"],
  Guyana: [
    "Barima-Waini",
    "Pomeroon-Supenaam",
    "Essequibo Islands-West Demerara",
    "Demerara-Mahaica",
    "Mahaica-Berbice",
    "East Berbice-Corentyne",
    "Cuyuni-Mazaruni",
    "Potaro-Siparuni",
    "Upper Takutu-Upper Essequibo",
    "Upper Demerara-Berbice",
  ],
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
    "Northwest Territories",
    "Nunavut",
    "Yukon",
  ],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
};

export const MAX_ADDITIONAL_FILES = 10;
export const MAX_ADDITIONAL_FILE_BYTES = 10 * 1024 * 1024;
export const ADDITIONAL_ACCEPT = ".pdf,.doc,.docx,.jpg,.jpeg,.png,.txt";
